# Network
MODEL_USE: mac
HIDDEN_SIZE: 512
DROPOUT: 0.15
MEMORY_GATE: False
SELF_ATTENTION: False
MAX_STEP: 12
WORD_EMBED_SIZE: 300

USE_GLOVE: False
# Execution
BATCH_SIZE: 64
LR_BASE: 0.0001
LR_DECAY_R: 0.2
LR_DECAY_LIST: [13, 15]
WARMUP_EPOCH: 3
MAX_EPOCH: 20
GRAD_NORM_CLIP: -1
GRAD_ACCU_STEPS: 1
LOSS_FUNC: ce
LOSS_REDUCTION: sum
OPT: Adam
OPT_PARAMS: {betas: '(0.9, 0.999)', eps: '1e-9'}